# Generated by Django 5.1.6 on 2025-02-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
